platform :ios, '12.0'

# lite version provides only map and some core services
target 'Lite' do
  # pod 'YandexMapsMobile', '4.13.0-lite'
end

# full version provides the rest of maps API
# routing, panoramas, search and etc.
target 'Full' do
  pod 'YandexMapsMobile', '4.13.0-full'
end
